/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lista.h"

bool_t
xdr_no (xdrs, objp)
	XDR *xdrs;
	no *objp;
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dado))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (no), (xdrproc_t) xdr_no))
		 return FALSE;
	return TRUE;
}
