/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lista.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

static void
listaprog_1(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		int init_1_arg;
		int insere_1_arg;
		int deleta_1_arg;
		int consulta_1_arg;
		int imprima_1_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (char *(*)()) init_1;
		break;

	case insere:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (char *(*)()) insere_1;
		break;

	case deleta:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (char *(*)()) deleta_1;
		break;

	case consulta:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (char *(*)()) consulta_1;
		break;

	case imprima:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (char *(*)()) imprima_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (argc, argv)
	int argc;
	char **argv;
{
	register SVCXPRT *transp;

	pmap_unset (LISTAPROG, LISTAVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, LISTAPROG, LISTAVER, listaprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LISTAPROG, LISTAVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, LISTAPROG, LISTAVER, listaprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LISTAPROG, LISTAVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
