/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTA_H_RPCGEN
#define _LISTA_H_RPCGEN

#include <rpc/rpc.h>


struct no {
	int dado;
	struct no *next;
};
typedef struct no no;

#define LISTAPROG 0x20000199
#define LISTAVER 1
#define init 1
extern  int * init_1();
#define insere 2
extern  int * insere_1();
#define deleta 3
extern  int * deleta_1();
#define consulta 4
extern  int * consulta_1();
#define imprima 5
extern  int * imprima_1();
extern int listaprog_1_freeresult ();

/* the xdr functions */
extern bool_t xdr_no ();

#endif /* !_LISTA_H_RPCGEN */
